// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADsIveEGsagai0k0EFUDdF-au0LVz7XC4',
    appId: '1:480441429440:web:cc9bf104c395742a552c25',
    messagingSenderId: '480441429440',
    projectId: 'recruiter-toolkit-ai',
    authDomain: 'recruiter-toolkit-ai.firebaseapp.com',
    storageBucket: 'recruiter-toolkit-ai.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdCldnhIeqLVTGqq5B9dAa04F2y8eqb0A',
    appId: '1:480441429440:android:e2144569d4f4ca3b552c25',
    messagingSenderId: '480441429440',
    projectId: 'recruiter-toolkit-ai',
    storageBucket: 'recruiter-toolkit-ai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV1cfnULUlp3qTrKUEnhuWzGWtWv--KAw',
    appId: '1:480441429440:ios:922e75167140ef27552c25',
    messagingSenderId: '480441429440',
    projectId: 'recruiter-toolkit-ai',
    storageBucket: 'recruiter-toolkit-ai.appspot.com',
    iosBundleId: 'com.example.sampleApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDV1cfnULUlp3qTrKUEnhuWzGWtWv--KAw',
    appId: '1:480441429440:ios:922e75167140ef27552c25',
    messagingSenderId: '480441429440',
    projectId: 'recruiter-toolkit-ai',
    storageBucket: 'recruiter-toolkit-ai.appspot.com',
    iosBundleId: 'com.example.sampleApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADsIveEGsagai0k0EFUDdF-au0LVz7XC4',
    appId: '1:480441429440:web:4f4509d4a856df55552c25',
    messagingSenderId: '480441429440',
    projectId: 'recruiter-toolkit-ai',
    authDomain: 'recruiter-toolkit-ai.firebaseapp.com',
    storageBucket: 'recruiter-toolkit-ai.appspot.com',
  );
}
